version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user root --pass password file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
