version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user root --pass password file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - SURREALDB_URL=http://surrealdb:8000
      - SURREALDB_USER=root
      - SURREALDB_PASS=password
      - SURREALDB_DATABASE=file:/data/database.db
      - SURREALDB_NS=upc
      - SURREALDB_DB=art_work
    volumes:
      - ./data:/data
